FROM node:25.6.1-alpine3.23

ENV NODE_ENV=production

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install

ADD . .

RUN npm run build

CMD [ "sh", "-c", "npm run preview -- --host 0.0.0.0 --port ${PORT:-8080}" ]
