FROM node:25.6.1-alpine3.23

ENV NODE_ENV=production

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install --production --ignore-scripts

ADD bin ./bin
ADD src ./src

CMD [ "npm", "start" ]